### ISSUE TITLE
R/sysdata.rda corrupted?

### ISSUE THREAD

**Issue by markskrass** [UrbanInstitute/uimapr#60]
Hello all! I was unable to install urbanmapr on my machine due to a problem loading the file sysdata.R. I received the following error message: 
`Warning: file ‘sysdata.rda’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(srcFile, e) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: unable to build sysdata DB for package ‘urbnmapr’
`
Looks like it should be easy to solve the problem by resaving `sysdata` with a more recent version. Please let me know if you need any more information to diagnose this problem!

**Comment by sstrochak** [comment]
hi @markskrass, can you tell me what version of R you are using?

**Comment by markskrass** [comment]
Hi Sarah! I'm running v 3.4.1, current as of June 2017. Do you think this is the problem?

Thanks so much for your help!
________________________________

**Comment by sstrochak** [comment]
most likely! I think if you update to 3.5 or later (I'd recommend the most recent version- 3.6.1), you should be able to install. If that doesn't work, let me know and we'll look for a solution!

**Comment by awunderground** [comment]
@markskrass Did this solve your issue?

**Comment by divz5** [comment]
It worked with installing 3.6 R version
