### ISSUE TITLE
adding a city polygon

### ISSUE THREAD

**Issue by krmaas** [UrbanInstitute/uimapr#61]
Thanks for this package it's making dipping my toes into mapping with R much easier.

I'm using your counties data, I would like to add a simple square polygon for a city. Can I just Rbind 4 rows (one for each corner)? What is the purpose of the order column? I'm using ggplot and don't have it anywhere in my code. Can I just increment from the highest value?

**Comment by ajjitn** [comment]
Sorry for the late response, but I would checkout the `tigris::places()` function which will allow you to read in the full polygon boundaries for any city (ie Census place) in the US. https://www.rdocumentation.org/packages/tigris/versions/1.4.1/topics/places
