### ISSUE TITLE
Is there a plan to publish package to CRAN again?

### ISSUE THREAD

**Issue by andreavargasmon** [UrbanInstitute/uimapr#65]
I really like this package, it provides a very easy way to do beautiful maps. I'm currently using it in a shiny application I'm developing and it's working just fine. But I did notice is not on CRAN and I don't know if it was at some point.

I would like to have this package on CRAN not only for the deployment of the app to be smoother but also because I truly thinks is a good tool. Do you have any plans on releasing it on CRAN? 

If you do, let me know how if I can help you with anything

**Comment by ajjitn** [comment]
Hi Andrea, as of right now I would say no, mostly because of data limitation issues with CRAN. We haven't updated the package in a while and are planning to work on some new updates soon that would potentially make it CRAN compliant but we don't want to make any promises!
