### ISSUE TITLE
Add Census Region polygon

### ISSUE THREAD

**Issue by erowlinson** [UrbanInstitute/uimapr#67]
Hello - Would it be possible to add a Census Region polygon to the list of available tibbles? I am mapping county-level data but would also like to delineate the Census regions (NE, MW, S, W) on the same map asshown here: [https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf]
I have tried adding the Census-provided shapefile for these regions as an additional layer, but as mentioned in other noted issues, the incompatible projection produces an unreadable map. Other suggestions for how to resolve this issue are welcome if there is an easier way to accomplish what I am seeking.
Many thanks in advance for your help and for the fantastic package!

**Comment by awunderground** [comment]
Thank you for this suggestion. I think the `tigris::regions()` and `tigris::shift_geometry()` functions can be used for this. We are trying to maintain a simple package so we aren't going to implement this change at this time.
